# Generated by Django 5.0.3 on 2024-03-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('redirect_link', models.TextField()),
                ('displayed_link', models.TextField()),
                ('favicon', models.TextField()),
                ('snippet', models.TextField()),
                ('snippet_highlighted_words', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
    ]
